# Generated by Django 4.1.5 on 2023-01-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSocialApp', '0003_remove_message_chat_delete_chat_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
